"""
LLM Engine Module.

This module provides a unified interface for interacting with large language models
through the LLMEngine class. The engine handles model initialization, text generation,
streaming, and resource management for all supported LLM providers.

The LLMEngine builds on the core engine structure and adapts it specifically
for language model operations with appropriate error handling and performance
optimizations.

Typical usage example:
    ```python
    from haive.core.models.llm.base import OpenAILLMConfig
    from haive.core.models.llm.engine import LLMEngine

    # Configure the LLM
    config = OpenAILLMConfig(
        model="gpt-4",
        cache_enabled=True
    )

    # Create the engine
    engine = LLMEngine(config)

    # Generate text
    response = engine.generate("Explain quantum computing in simple terms.")
    print(response)

    # Use streaming for long responses
    for chunk in engine.generate_stream("Tell me a story about a robot."):
        print(chunk, end="", flush=True)
    ```
"""

from __future__ import annotations

from typing import Any, Iterator, Optional

from haive.core.engine.base import CoreEngine
from haive.core.models.llm.base import LLMConfig


class LLMEngine(CoreEngine[LLMConfig]):
    """
    Large Language Model engine implementation.

    This class provides a unified interface for working with various LLM providers,
    handling model initialization, generation, streaming, and resource management.

    The engine is designed to:
    - Lazily initialize models only when needed
    - Provide consistent generation methods across providers
    - Support both synchronous and streaming text generation
    - Properly manage resources through cleanup methods
    - Handle common error conditions

    Attributes:
        config: The LLM configuration object
        _model: The underlying LLM model instance (initialized on demand)
    """

    def __init__(self, config: LLMConfig):
        """
        Initialize a new LLM engine with the given configuration.

        Args:
            config: Configuration for the LLM model containing provider,
                model name, API credentials, and other settings
        """
        super().__init__(config)

    def initialize(self) -> None:
        """
        Initialize the LLM model if not already initialized.

        This method is called automatically by generation methods
        and ensures the model is only initialized once.
        """
        if self._model is None:
            self._model = self.config.instantiate()

    def cleanup(self) -> None:
        """
        Clean up resources used by the LLM model.

        This method releases the model instance and frees associated resources.
        The engine can be reinitialized after cleanup by calling initialize()
        or any generation method.
        """
        self._model = None

    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate text from a prompt.

        This method sends the prompt to the LLM and returns the complete
        generated response as a string.

        Args:
            prompt: The input prompt text
            **kwargs: Additional keyword arguments to pass to the model's
                generation method, such as temperature, max_tokens, etc.

        Returns:
            The generated text response

        Raises:
            RuntimeError: If model initialization fails
        """
        self.initialize()
        response = self._model.invoke(prompt, **kwargs)
        return response.content

    def generate_stream(self, prompt: str, **kwargs) -> Iterator[str]:
        """
        Generate text from a prompt in streaming mode.

        This method returns an iterator that yields text chunks as they
        are generated by the model, enabling real-time display of responses.

        Args:
            prompt: The input prompt text
            **kwargs: Additional keyword arguments to pass to the model's
                streaming method, such as temperature, max_tokens, etc.

        Yields:
            Text chunks as they are generated

        Raises:
            RuntimeError: If model initialization fails or if the model
                doesn't support streaming
        """
        self.initialize()
        for chunk in self._model.stream(prompt, **kwargs):
            yield chunk.content

    def get_model(self) -> Optional[Any]:
        """
        Get the underlying LLM model instance.

        This method provides access to the raw model object for advanced
        operations not covered by the standard interface.

        Returns:
            The LLM model instance, or None if not initialized
        """
        return self._model
